### ISSUE TITLE
Variable detection within AF Elements query broken in editor mode

### ISSUE THREAD

**Issue by aballinEH2** [GridProtectionAlliance/osisoftpi-grafana#142]
When I was running Grafana 9.4.3 using the OSIsoft-PI plugin version 2.0.0 (or possibly 2.1.1), there was a bug with including Grafana dashboard variables as part of the AF path query. Screen shot below is from a dashboard containing `location` and `system` variables.
![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/145640797/63f752c3-ce33-4278-8f97-73a386291d3e)
The segment `Unit${system}` is white, indicating that the presence of the variable isn't detected, and I can't further navigate down the asset tree. This is confirmed when I switch to raw query mode where 'Unit${system}' is replaced with 'undefined'.
![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/145640797/cb9ba07e-12df-4e9a-97f0-b10d83a74e3f)
Upgrading the plugin to version 4.2.0 fixed this issue (the segment would show up in blue text and I could further navigate in the asset tree), but upgrading to Grafana 10.2.3 seems to have broken the fix. Any chance this can be remedied again? Thanks!

**Comment by alexl04** [comment]
In addition, could it be that there is a limit to the amount of AF Attributes shown/received from the API? In below example we have 6000+ attributes. If I try to find some attribute starting with the T (after CP1_) by typing "CP1_T" we do not receive any attributes at all. If I type "CP1_A" we do receive all attributes that contain that string. By scrolling through the asset tree we can see that it stops at "G". So could it be that the AF attribute query is send once instead of every time we enter some search?

<img width="739" alt="image" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/08b49b7a-49e6-4f6a-b636-8ec9695ea32e">

**Comment by coderReview** [comment]
Fixed in #150

**Comment by alexl04** [comment]
> Fixed in #150

Tested with grafana 11 and plugin v5 beta > cannot confirm that it is fixed. I experience the same issue as described above.

**Comment by pvmagacho-nde** [comment]
For v5.0.0 I am increasing the max attributes count to 10000. I next versions I can check if we can improve this
