### ISSUE TITLE
Edge & Internet Explorer: cache-control header may not be specified on bulk data requests

### ISSUE THREAD

**Issue by WimDeRons** [GridProtectionAlliance/osisoftpi-grafana#8]
Hello,

We have observed the following when using a Graph panel which uses 6 PI tags:
- Chrome & Firefox: works fine
![datapointssmall](https://user-images.githubusercontent.com/4091094/33942419-2470c3ea-e016-11e7-9738-c3cd76f16b7d.png)
- Edge & Internet Explorer: no data points
![nodatapointssmall](https://user-images.githubusercontent.com/4091094/33942339-ead94594-e015-11e7-8dbb-9ba922f8c810.png)

In Edge & IE the query inspector mentions the following message: "Cache-Control header may not be specified on bulk data requests."
![queryinspector](https://user-images.githubusercontent.com/4091094/33942511-775f8140-e016-11e7-9704-51e8fcac6418.png)

This issue is also present when using other panels, for example:
- singlestat
- heatmap
- table
- pie chart

Would you be able to offer any insight how to resolve this issue?
Thank you in advance for your time and effort!

Kind regards,
Wim

**Comment by ritchiecarroll** [comment]
I assume not using IE/Edge is an option ;-)

I did find this, your issue may have more to do with the PI Web API Cache:
https://pisquare.osisoft.com/thread/9282

**Comment by EEParker** [comment]
Following up to @ritchiecarroll's comment, 

From the OSISoft documentation:

> Note:
Use of the Cache-Control header is not permitted on bulk data operations by default, due to performance considerations. However, this setting can be changed by adding/setting a Runtime configuration setting `IgnoreCacheControlForBulkRequests` to `true`.

Source: 
https://livelibrary.osisoft.com/LiveLibrary/web/pub.xql?c=t&action=home&pub=web-api-v5&lang=en&pub_category=PI%20Web%20API&pub_cat_loc=Web%20API#addHistory=true&filename=GUID-73932E56-CF12-4641-A01C-6C310784680F.xml&docid=GUID-B7168067-94C5-4E99-96B7-6098B9501261&inner_id=&tid=&query=&scope=&resource=&toc=false&eventType=lcContent.loadDocGUID-B7168067-94C5-4E99-96B7-6098B9501261

Additional info on how to modify runtime configuration:
https://livelibrary.osisoft.com/LiveLibrary/web/pub.xql?c=t&action=home&pub=web-api-v5&lang=en&pub_category=PI%20Web%20API&pub_cat_loc=Web%20API#addHistory=true&filename=GUID-795C947E-C220-4521-8827-F7840CFE0DEA.xml&docid=GUID-98930EB1-36D9-435A-8D3E-626BC9D45DEB&inner_id=&tid=&query=&scope=&resource=&toc=false&eventType=lcContent.loadDocGUID-98930EB1-36D9-435A-8D3E-626BC9D45DEB

**Comment by WimDeRons** [comment]
Thanks for your replies!

Not using IE/Edge is indeed an option, but unfortunately that choice is not under my control.

I've added the "IgnoreCacheControlForBulkRequests" configuration attribute on our test environment, and can confirm this resolves the issue. Of course I'll have to provide some argumentation why we are considering disabling a default performance setting if this is to go to production. And this is the reason why I was hoping that this could be resolved by changing the configuration of IE/Edge (or perhaps the data source plugin itself), instead of changing the configuration of the PI Web API.

Thanks for your feedback and Happy Holidays!

**Comment by EEParker** [comment]
From the documentation it looks as though it doesn't actually change the performance of PI WebAPI, just _ignores_ that HTTP Header instead of throwing an error when the browser tries to include it.
